import type { Metadata } from "next";
import Navbar from "../../components/Navbar";
import "./globals.css";
import ClientProviders from "./providers"; // We'll make this

export const metadata: Metadata = {
  title: "Consistify",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <Navbar />
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}